* ColorCode - ColorAdd, browser extension.

** Description: 
ColorCode - ColorAdd* is an extension built on code from the Eye Dropper project, which is a web browser extension that helps you recognize and learn symbols
of web page colors using the ColorAdd symbols. Currently works on Chromium and Google Chrome.*

* Licenses 
**Eye Dropper extension, the use is made possible through a released under a [MIT License] [[/blob/master/LICENSE]].
**ColorAdd, the use is made possible through a pro bono license. (Schools and universities are exempt from paying fees in a pro bono model, with this licensing in the education sector managed by the non-profit association ColorADD.Social.)

<h2 align="center"> Related technologies: </h2>
<h3 align="center">
    <a href="https://www.coloradd.net/en/coloradd-code/">🔗 ColorAdd</a>
</h3> <p align="center">🕵️‍♀️ Color identification system for color blind people.</p>
<h3 align="center">
<a href="http://github.com/kepi/chromeEyeDropper">🔗 ChromeEyeDropper</a>
</h3> <p align="center">🚀 Eye Dropper is web browser extension which helps you pick and manage palettes of colors from web pages or color picker. It currently works in Chromium and Google Chrome™.</p>

<h2> steps to compile the yarn project </h2>

```bash
1) install nodejs (comes with npm)
2) install yarn with the command "npm install -g yarn"
3) clone the project
4) inside the cloned project directory, install the project dependencies with the "yarn" command
5) run the "yarn run watch" command so that any changes to the project are automatically compiled
5) the compiled code of the project will be in the "dist" folder. you can load this folder in chrome extensions to install the extension in the browser
```

<h2 style="color: red"> Warning: The application will stop working in 2024, due to a change in the version of the browsers' DOM manisfet. </h2>
